### ISSUE TITLE
An option when setting up

### ISSUE THREAD

**Issue by oathzed** [SHSharkar/Stremio-Real-Debrid-Addon#3]
Hello,

Can we please have an option when setting up the addon for install.

To just have all torrents together (movies, shows)

And all downloads to be together (movies, shows)

I mainly use my debrid cloud where I send it one offs where I can't find movies or shows on other addons, just so it's quick to find and play something. Thank you!!

**Comment by SHSharkar** [comment]
@oathzed ,

Thanks for your comments. The addon was designed to work in a way that it is currently having. to separate the movies and TV shows.

And the source code is open. You are welcome to fork the repository and adjust accordingly to your needs.

P.S.: I have recently released **v1.0.5** which has made a lot of changes since then.

**Comment by oathzed** [comment]
> @oathzed ,
> 
> Thanks for your comments. The addon was designed to work in a way that it is currently having. to separate the movies and TV shows.
> 
> And the source code is open. You are welcome to fork the repository and adjust accordingly to your needs.
> 
> P.S.: I have recently released **v1.0.5** which has made a lot of changes since then.

Ahh ok, I'm not the best programmer, is there anyway you can help me on how I might make it so they're merged together? I'd love to fork it and do that, I can figure out the hosting aspect, but the programming is a bit tricky.

Thanks again for all your help
